export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_PROFESSORS = 'FETCH_PROFESSORS';
export const FETCH_STUDENT_PROFILE = "FETCH_STUDENT_PROFILE";
export const FETCH_PROFESSOR_PROFILE = "FETCH_PROFESSOR_PROFILE";

