export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_PROFESSORS = 'FETCH_PROFESSORS';
export const FETCH_STUDENT_PROFILE = "FETCH_STUDENT_PROFILE";
export const FETCH_PROFESSOR_PROFILE = "FETCH_PROFESSOR_PROFILE";
export const FILTER_CATALOG_STUDY = "FILTER_CATALOG_STUDY";
export const FILTER_CATALOG_YEAR = "FILTER_CATALOG_YEAR";
export const FILTER_CATALOG_SEMESTER = "FILTER_CATALOG_SEMESTER";
export const FETCH_CATALOG = "FETCH_CATALOG";