export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_PROFESSORS = 'FETCH_PROFESSORS';
export const NEW_STUDENT = 'NEW_STUDENT';
export const FETCH_STUDENT_COURSES = 'FETCH_STUDENT_COURSES';
export const NEW_STUDENT_COURSE = 'NEW_STUDENT_COURSE'; 